#:kivy 2.0.0

#### Layout
<Container>
    orientation: 'vertical'
    spacing: 10
    size: 600, 1024

    BoxLayout:
        orientation: "horizontal"
        size_hint: None, None # ich muss erst hint auschalten samit size geht
        size: 600, 200
        BoxLayout:
            orientation: "vertical"
            BoxLayout:
                orientation: "horizontal"
                Label:
                    text: "WIDTH:"
                Label:
                    text: "25°"
            BoxLayout:
                orientation: "horizontal"
                Label:
                    text: "REVERB:"
                Label:
                    text: "25%"
        BoxLayout:
            orientation: "vertical"
            BoxLayout:
                orientation: "horizontal"
                Label:
                    text: "WIDTH:"
                Label:
                    text: "25°"
            BoxLayout:
                orientation: "horizontal"
                Label:
                    text: "REVERB:"
                Label:
                    text: "25%"
        BoxLayout:
            orientation: "vertical"
            BoxLayout:
                orientation: "horizontal"
                Label:
                    text: "WIDTH:"
                Label:
                    text: "25°"
            BoxLayout:
                orientation: "horizontal"
                Label:
                    text: "REVERB:"
                Label:
                    text: "25%"
        BoxLayout:
            orientation: "vertical"
            BoxLayout:
                orientation: "horizontal"
                Label:
                    text: "WIDTH:"
                Label:
                    text: "25°"
            BoxLayout:
                orientation: "horizontal"
                Label:
                    text: "REVERB:"
                Label:
                    text: "25%"


# mein Weidget
    MotionDisplay:
        pos_ind_ch1: pos_ind_ch1
        pos_ind_ch2: pos_ind_ch2
        pos_ind_ch3: pos_ind_ch3
        pos_ind_ch4: pos_ind_ch4

        size_hint: None, None # ich muss erst hint auschalten samit size geht
        size: 600, 600

        PositionIndicator:
            id: pos_ind_ch1
            center: self.parent.center
        PositionIndicator:
            id: pos_ind_ch2
            center: self.parent.center
        PositionIndicator:
            id: pos_ind_ch3
            center: self.parent.center
        PositionIndicator:
            id: pos_ind_ch4
            center: self.parent.center


# Zeile 1
    BoxLayout:
        orientation: "horizontal"
        size_hint: None, None # ich muss erst hint auschalten samit size geht
        size: 600, 200

        BoxLayout:
            orientation: "vertical"
            Label:
                text: "MODE: MONO"
            Label:
                text: "BEAT: 1/4"
            Label:
                text: "BARS: 4"
            Label:
                text: "BMP: 128"
        
        BoxLayout:
            orientation: "vertical"
            Label:
                text: "MODE: MONO"
            Label:
                text: "BEAT: 1/4"
            Label:
                text: "BARS: 4"
            Label:
                text: "BMP: 128"

        BoxLayout:
            orientation: "vertical"
            Label:
                text: "MODE: MONO"
            Label:
                text: "BEAT: 1/4"
            Label:
                text: "BARS: 4"
            Label:
                text: "BMP: 128"

        BoxLayout:
            orientation: "vertical"
            Label:
                text: "MODE: MONO"
            Label:
                text: "BEAT: 1/4"
            Label:
                text: "BARS: 4"
            Label:
                text: "BMP: 128"
    
# FussZeile
    Label:
        text: "RCV:192.168.178.125:1234|SND:192.168.178.126:1232|BPM:128"



#### Wedgets
<MotionDisplay>
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size
            source: "Pix/MoverMeterBG.png"


<PositionIndicator>
    size: 50, 50
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size
